using System.Collections.Generic;

namespace RobotsWantedLeague.Models
{
    public class Country
    {
        public string Name { get; set; }
        public string Region { get; set; }
    }

    public static class CountryData
    {
        public static readonly List<Country> data = new List<Country>
        {
            
            new Country { Name = "Croatia", Region = "Europe" },
            new Country { Name = "Cuba", Region = "North America" },
            new Country { Name = "Cyprus", Region = "Europe" },
            new Country { Name = "Czech Republic", Region = "Europe" },
            new Country { Name = "Denmark", Region = "Europe" },
            new Country { Name = "Djibouti", Region = "Africa" },
            new Country { Name = "Dominica", Region = "North America" },
            new Country { Name = "Dominican Republic", Region = "North America" },
            new Country { Name = "Ecuador", Region = "South America" },
            new Country { Name = "Egypt", Region = "Africa" },
            new Country { Name = "El Salvador", Region = "North America" },
            new Country { Name = "Equatorial Guinea", Region = "Africa" },
            new Country { Name = "Eritrea", Region = "Africa" },
            new Country { Name = "Estonia", Region = "Europe" },
            new Country { Name = "Eswatini", Region = "Africa" },
            new Country { Name = "Ethiopia", Region = "Africa" },
            new Country { Name = "Fiji", Region = "Oceania" },
            new Country { Name = "Finland", Region = "Europe" },
            new Country { Name = "France", Region = "Europe" },
            new Country { Name = "Gabon", Region = "Africa" },
            new Country { Name = "Gambia", Region = "Africa" },
            new Country { Name = "Georgia", Region = "Asia" },
            new Country { Name = "Germany", Region = "Europe" },
            new Country { Name = "Ghana", Region = "Africa" },
            new Country { Name = "Greece", Region = "Europe" },
            new Country { Name = "Grenada", Region = "North America" },
            new Country { Name = "Guatemala", Region = "North America" },
            new Country { Name = "Guinea", Region = "Africa" },
            new Country { Name = "Guinea-Bissau", Region = "Africa" },
            new Country { Name = "Guyana", Region = "South America" },
            new Country { Name = "Haiti", Region = "North America" },
            new Country { Name = "Honduras", Region = "North America" },
            new Country { Name = "Hungary", Region = "Europe" },
            new Country { Name = "Iceland", Region = "Europe" },
            new Country { Name = "India", Region = "Asia" },
            new Country { Name = "Indonesia", Region = "Asia" },
            new Country { Name = "Iran", Region = "Asia" },
            new Country { Name = "Iraq", Region = "Asia" },
            new Country { Name = "Ireland", Region = "Europe" },
            new Country { Name = "Israel", Region = "Asia" },
            new Country { Name = "Italy", Region = "Europe" },
            new Country { Name = "Jamaica", Region = "North America" },
            new Country { Name = "Japan", Region = "Asia" },
            new Country { Name = "Jordan", Region = "Asia" },
            new Country { Name = "Kazakhstan", Region = "Asia" },
            new Country { Name = "Kenya", Region = "Africa" },
            new Country { Name = "Afghanistan", Region = "Asia" },
            new Country { Name = "Åland Islands", Region = "Europe" },
            new Country { Name = "Albania", Region = "Europe" },
            new Country { Name = "Algeria", Region = "Africa" },
            new Country { Name = "Andorra", Region = "Europe" },
            new Country { Name = "Angola", Region = "Africa" },
            new Country { Name = "Antigua and Barbuda", Region = "North America" },
            new Country { Name = "Argentina", Region = "South America" },
            new Country { Name = "Armenia", Region = "Asia" },
            new Country { Name = "Australia", Region = "Oceania" },
            new Country { Name = "Austria", Region = "Europe" },
            new Country { Name = "Azerbaijan", Region = "Asia" },
            new Country { Name = "Bahamas", Region = "North America" },
            new Country { Name = "Bahrain", Region = "Asia" },
            new Country { Name = "Bangladesh", Region = "Asia" },
            new Country { Name = "Barbados", Region = "North America" },
            new Country { Name = "Belarus", Region = "Europe" },
            new Country { Name = "Belgium", Region = "Europe" },
            new Country { Name = "Belize", Region = "North America" },
            new Country { Name = "Benin", Region = "Africa" },
            new Country { Name = "Bhutan", Region = "Asia" },
            new Country { Name = "Bolivia", Region = "South America" },
            new Country { Name = "Bosnia and Herzegovina", Region = "Europe" },
            new Country { Name = "Botswana", Region = "Africa" },
            new Country { Name = "Brazil", Region = "South America" },
            new Country { Name = "Brunei", Region = "Asia" },
            new Country { Name = "Bulgaria", Region = "Europe" },
            new Country { Name = "Burkina Faso", Region = "Africa" },
            new Country { Name = "Burundi", Region = "Africa" },
            new Country { Name = "Cambodia", Region = "Asia" },
            new Country { Name = "Cameroon", Region = "Africa" },
            new Country { Name = "Canada", Region = "North America" },
            new Country { Name = "Cape Verde", Region = "Africa" },
            new Country { Name = "Central African Republic", Region = "Africa" },
            new Country { Name = "Chad", Region = "Africa" },
            new Country { Name = "Chile", Region = "South America" },
            new Country { Name = "China", Region = "Asia" },
            new Country { Name = "Colombia", Region = "South America" },
            new Country { Name = "Comoros", Region = "Africa" },
            new Country { Name = "Congo", Region = "Africa" },
            
        };
    }
}
